[package]
name = "kulupu-pow"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
consensus-pow = { package = "substrate-consensus-pow", path = "../vendor/substrate/client/consensus/pow" }
consensus-pow-primitives = { package = "substrate-consensus-pow-primitives", path = "../vendor/substrate/primitives/consensus/pow" }
sr-primitives = { path = "../vendor/substrate/primitives/sr-primitives" }
primitives = { package = "substrate-primitives", path = "../vendor/substrate/primitives/core" }
client-api = { package = "substrate-client-api", path = "../vendor/substrate/client/api" }
randomx = { path = "../vendor/randomx" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
log = "0.4"
kulupu-primitives = { path = "../primitives" }
kulupu-runtime = { path = "../runtime" }
consensus-common = { package = "substrate-consensus-common", path = "../vendor/substrate/primitives/consensus/common" }
inherents = { package = "substrate-inherents", path = "../vendor/substrate/primitives/inherents" }
lru-cache = "0.1"
rand = { version = "0.7", features = ["small_rng"] }
