[package]
name = "kulupu-randomx-sys"
description = "FFI bindings for RandomX"
license = "BSD-3-Clause"
version = "1.3.0"
authors = ["Wei Tang <wei@that.world>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.49"
cmake = "0.1"
