[package]
name = "kulupu-randomx-sys"
description = "FFI bindings for RandomX"
license = "GPL-3.0-or-later"
version = "2.2.1"
authors = ["Wei Tang <wei@that.world>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.54"
cmake = "0.1"
